version: 3
networks:
  web:
    external: true
services:
  srtdash:
    # build: ./app
    image: mikeryan56/starlette-srtdash:19.8.10
    # image: mikeryan56/starlette-srtdash:latest
    restart: always
    ports:
    - "5000"
    volumes:
    - .:/code


    environment:
    # Application information
    - APP_VERSION=20.03.07
    - OWNER=your name
    - WEBSITE=https://yoursite.com/support
    # Application Configuration
    - HOST_DOMAIN=https://yourdomain.com
    - DEBUG=True
    - RELEASE_ENV=dev
    #prd for production or dev for development
    - SQLALCHEMY_DATABASE_URI=sqlite:///sqlite_db/api.db
    - SECRET_KEY=<your-secret>
    - GITHUB_CLIENT_ID=<your-client-id>
    - GITHUB_CLIENT_SECRET=<your-client-secret>
    - MOCK_GITHUB=False
    # Loguru settings
    - LOGURU_RETENTION=10 days
    - LOGURU_ROTATION=100 MB
    # Leave intact for license
    - CREATED_BY=Mike Ryan
    - LICENSE_TYPE=MIT
    - LICENSE_LINK=https://github.com/devsetgo/test-api/blob/master/LICENSE

    #if using traefik
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.stardash.rule=Host(`stardash.devsetgo.com`)"
    - "traefik.http.routers.stardash.entrypoints=websecure"
    - "traefik.http.routers.stardash.tls.certresolver=mytlschallenge"
    networks:
      - web
  # deploy:
  #    replicas: 2
  #    resources:
  #      limits:
  #        cpus: "2"
  #        memory: 100M
#      restart_policy:
#        condition: always
